spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/medical_db

  jpa:
    hibernate:
      ddl-auto: update

# JWT config
jwt:
  secret: heladslkasdaskdlasdjldasldaslkdasdlaskdalkdjlkasjldkjaslk
  expiration: 1

# Redis config
redis:
  host: cache
  port: 6379

debug: true