debug: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  banner:
    location: classpath:banner/banner.txt
  application:
    name: Medical App

  jpa:
    hibernate:
      ddl-auto: update
redis:
  host: cache
  port: 6379


jwt:
  secret: heladslkasdaskdlasdjldasldaslkdasdlaskdalkdjlkasjldkjaslk
  expiration: 36000